---

- hosts: all
  become: true
  tasks:

  - name: install apache package & add php support for apache & update the system
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package  }}"
      state: latest
      update_cache: yes
