---

- hosts: all
  become: true
  tasks:

### Playbook for Debian and Ubuntu ###

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

### Playboot for Fedora ###

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Fedora"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Fedora"

### Palybook for CentOS ###

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
