---

- hosts: all
  become: true
  tasks:

### Playbook for Debian base distributions ###
  - name: install apache2 package & add php support for apache & update the system
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

### Playbook for Fedora distribution ###

  - name: install apache2 package & add php support for apache & update the system
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"

### Palybook for CentOS distribution ###

  - name: install apache2 package & add php support for apache & update the system

    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

